apiVersion: apps/v1
kind: Deployment
metadata:
  name: gacoapp
  labels:
    app: gacoapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gacoapp
  template:
    metadata:
      labels:
        app: gacoapp
    spec:
      containers:
      - name: gacoapp
        image: crgacoa.azurecr.io/gacoapp/gacoapp:latest
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 1000m
            memory: 512Mi
        readinessProbe: # is the container ready to receive traffic?
          httpGet:
            port: 3000
            path: /
        livenessProbe: # is the container healthy?
          httpGet:
            port: 3000
            path: /